[package]
name = "fifo-accounting"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = { version = "0.26.1", features = [ "dates" ] }
chrono = "0.4.38"
env_logger = "0.11.5"
log = "0.4.22"
rust_decimal = "1.36.0"
