[package]
name = "fifo-types"
version = "0.1.0"
edition = "2021"

[dependencies]

# External dependencies
chrono = "0.4.38"
log = "0.4.22"
rust_decimal = "1.36.0"
serde = { version = "1.0.216", features = ["derive"] }
